
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - portalcontroleinternos

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: npm install, build
        run: |
          npm install
          npm run build --if-present
        # As per your request, we are building without Azure variables.
        # If the build fails or the deployed app has issues,
        # it will be because build-time environment variables are needed here.
        # They can be added as GitHub repository secrets.
        # env:
        #   SHAREPOINT_TENANT_ID: ${{ secrets.SHAREPOINT_TENANT_ID }}
        #   SHAREPOINT_CLIENT_ID: ${{ secrets.SHAREPOINT_CLIENT_ID }}
        #   SHAREPOINT_CLIENT_SECRET: ${{ secrets.SHAREPOINT_CLIENT_SECRET }}
        #   SHAREPOINT_SITE_URL: ${{ secrets.SHAREPOINT_SITE_URL }}
